
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tubuyakikun_development

test:
  <<: *default
  database: tubuyakikun_test


production:
  <<: *default
  database: tubuyakikun_production
  username: tubuyakikun
  password: <%= ENV['TUBUYAKIKUN_DATABASE_PASSWORD'] %>
